### ISSUE TITLE
Tags and versionname do not match

### ISSUE THREAD

**Issue by ghost** [WeAreFairphone/android_packages_apps_MyContactsWidget#2]
While I guess you start from 1.0 again after outsourcing this app, the tag says `1.0.1`, but androids own version (as specified in the AndroidManifest.xml) is 2.1 -- I think in the future you should bump your tags to the same 2.x version scheme.

**Comment by Roboe** [comment]
Absolutely right, Ö
Will bump the tag on next release, ;)
Thanks!
