### ISSUE TITLE
Change package name (causes signature conflict with Fairphone Open OS)

### ISSUE THREAD

**Issue by Roboe** [WeAreFairphone/android_packages_apps_MyContactsWidget#4]
douwe at [Fairphone Forum](https://forum.fairphone.com/t/publishing-fairphone-specific-apps-launcher-contact-widget-on-f-droid/28008/50?u=roboe):
> Hey all, one thing we noticed here at Fairphone: the package name of the app can not be the same as the original package for two reasons:
>
>  - it will cause a conflict with the signature of our version of the app and the installation might fail.
>  - people might get confused about the creator of these apps. So referencing Fairphone as the origin of this code is fine, but it should be clear it is a community (WeAreFairphone) project now.
>
> Keep on pushing!

It has already caused troubles:
https://forum.fairphone.com/t/publishing-fairphone-specific-apps-launcher-contact-widget-on-f-droid/28008/54
https://forum.fairphone.com/t/my-contacts-widget-wont-update-wont-uninstall/28767 (related with how F-Droid manages [cross-developer updates](https://gitlab.com/fdroid/fdroidclient/issues/122) and [erratic indications](https://gitlab.com/fdroid/fdroidclient/issues/628), though)

Steps to follow:
 - [x] Remove WeAreFairphone apps with `com.fairphone` package namespace from F-Droid:
   - [x] Release new virtual versions with a [What's New](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#changelogs-whats-new) section for each app
   - [x] Disable current apps ([docs](https://f-droid.org/manual/html_node/Disabled.html#Disabled))
 - [x] Change package's namespace and resubmit them on F-Droid ([metadata](https://gitlab.com/fdroid/fdroiddata))

How should we do this? @jannispinter

**Comment by jannispinter** [comment]
Changing the package's namespace and reupload shouldn't be a problem. F-Droid says that they don't remove apps. In this case however, they might make an exception. I will open a ticket at F-Droid.

**Edit:** Opened [here](https://gitlab.com/fdroid/fdroiddata/issues/736).

**Comment by Roboe** [comment]
So, steps to follow (updated above):

- Release new virtual versions with a [What's New](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#changelogs-whats-new) section for each app
- Disable current apps ([docs](https://f-droid.org/manual/html_node/Disabled.html#Disabled))
- Change signatures of apps. Add metadata for the "new apps" (i.e. submitting them on F-Droid)

**Comment by jannispinter** [comment]
I'm a bit busy this week and might not be able to get this done until the weekend. Feel free to make the changes, if you have the spare time.

**Comment by Roboe** [comment]
Update: https://gitlab.com/fdroid/fdroiddata/issues/736#note_30848046

I created new `old-package-name` branches for both apps and tried to setup the changelogs.
I will create tags and update F-Droid's metadata once we ensure this will work fine.

I will change package names now on the `master` branch and update tags to fit real version (this shouldn't break anything on F-Droid side).

**Comment by Roboe** [comment]
New apps had hit F-Droid. Old apps had been marked with a "deprecation notice". We only need to disable them in the next F-Droid index update. Will keep this issue open until then, ;)

**Comment by Roboe** [comment]
I've submited last step needed to close this issue to F-Droid's data repo: https://gitlab.com/fdroid/fdroiddata/merge_requests/2339

**Comment by Roboe** [comment]
Closing this since it was fulfilled time ago.
